### PR TITLE
CS fix

### PR DESCRIPTION
**Pull request by giorrrgio**
Just a pass of cs-fixer, composer.lock added to .gitignore

### CODE REVIEW

**Comment by eux** [comment]
composer.lock should NOT be added to .gitignore @giorrrgio it must be part of the repo to lock the dependencies

**Comment by garak** [comment]
I agree with @giorrrgio composer.lock should be ignored in bundles (but not in projects)

**Comment by giorrrgio** [comment]
I agree with me too, and with the majority of great symfony bundles out there @eux :-)

**Comment by eux** [comment]
:+1:  I disagree with myself, sorry :smile:

**Comment by mmenozzi** [comment]
Thank you!

**Pull request merged**
